server:
  port: 8080

spring:
  application:
    name: user-service
app:
  jwt:
    secret: ${APP_JWT_SECRET}
    accessTokenMinutes: 60
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId}] %-5level %logger{36} - %msg%n"
  file:
    name: logs/user-service.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}