spring:
  application:
    name: order-service
app:
  jwt:
    secret: ${APP_JWT_SECRET}
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId}] %-5level %logger{36} - %msg%n"
  file:
    name: logs/order-service.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka